### ISSUE TITLE
Unit test is not done

### ISSUE THREAD

**Issue by jadeden1999** [Jamill-hallak/nfts-uinttest#1]
Please use how to run the code in the readme .md by any developer 
also you did not test and verify the numbers of withdrawn eth in the payment splitter which is the most important

**Comment by Jamill-hallak** [comment]
Please install  :
_Visual Studio Code
_ nodejs : https://nodejs.org/en/download/ .
_npm ;https://docs.npmjs.com/downloading-and-installing-node-js-and-npm.
_ganache-cli : npm install -g ganache-cli  , Yarn: yarn global add ganache-cli 
_truffle : npm install -g truffle,


run in command  : ganache-cli --allowUnlimitedContractSize

inside the folder of uint test :
install :   merkltreejs : npm install merkletreejs
              keccak256: npm install keccak256
to run test : type in Visual Studio Code  terminal :truffle test 
![uinttest helper](https://user-images.githubusercontent.com/79945615/173589803-e6dcb6e0-a240-40d1-9ac0-8935809485d6.png)
